import { Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar/Navbar";
import Footer from "@/components/Shared/Footer";
import Providers from "./lib/provider";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  subsets: ["latin"],
  weight: "400"
});





export const metadata = {
  title: "KeenKeeper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#F8FAFC]">
        <Providers>
          <Navbar />
          {children}
          <Footer />

          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}
